### ISSUE TITLE
ENV_VAULT_EDITOR

### ISSUE THREAD

**Issue by bonelifer** [romantomjak/env-vault#1]
Possibly have it check for $`ENV_VAULT_EDITOR and use that if it exists before using $EDITOR. For most things I like to use nano, but for env files, I'd rather use pluma. Otherwise, I went from wanting to kill myself after trying to figure out Vault to just using env-vault. Greatly simplifies everything. Extremely great substitute for this homelabber.`

**Comment by romantomjak** [comment]
Thanks for the kind words and for raising this issue. I think it's a great suggestion! I'll have a look at this some time this week and will close the issue once it's addressed 👍

**Comment by romantomjak** [comment]
This should be available in the 0.3.0 release. Thanks for contributing! ❤️
