### ISSUE TITLE
More complete Makefile

### ISSUE THREAD

**Issue by bonelifer** [romantomjak/env-vault#2]
I thought I'd share this. I tried to make it as nub proof as possible.  Ah, persistence and google fu, out foxed my non-existent knowledge of makefiles. The below alias can be run in a new composer folder to copy the Makefile to the current directory. I chose to allow regular docker-compose up -d, when the prod.env doesn't exist as to not force it's use on containers that don't use secrets.
 
~./bash_aliases
```
alias mkmake="cp ~/bin/staging/Makefile ."
```
*****

```
.DEFAULT_GOAL := default

up:
	-@if [ ! -f ./prod.env ]; then \
	  docker-compose up -d;\
	 else \
	  env-vault prod.env docker-compose -- up -d;\
	 fi ; \

edit:
	-@if [ ! -f ./prod.env ]; then \
	  echo "prod.env doesn't exist, please run the command below to create the file.";\
	  echo "make init";\
	 else \
	  env-vault edit prod.env;\
	 fi ; \

decrypt:
	-@if [ ! -f ./prod.env ]; then \
	  echo "prod.env doesn't exist, please run the command below to create the file.";\
	  echo "make init";\
	 else \
	  env-vault decrypt prod.env;\
	 fi ; \

encrypt:
	-@if [ ! -f ./prod.env ]; then \
	  echo "prod.env doesn't exist, please run the command below to create the file.";\
	  echo "make init";\
	 else \
	  env-vault encrypt prod.env;\
	 fi ; \

init:
	-@if [ -f ./prod.env ]; then \
	  echo "prod.env already exists";\
	 else \
	   env-vault create prod.env;\
	 fi ; \

default:
	@ echo " ";\
	echo "make up      - bring up the container";\
	echo "make edit    - edit the prod.env secrets file";\
	echo "make decrypt - decrypt the prod.env secrets file";\
	echo "make encrypt - re-encrypt the prod.env secrets file";\
	echo "make init    - create the prod.env secrets file";\
```

**Comment by romantomjak** [comment]
Thanks for opening the issue! My personal opinion is that Makefiles usually end up highly customized to fit one's individual needs, so I wouldn't necessarily want to force one or another style of writing Makefiles onto anyone. That being said, I do believe this is valuable documentation. Shall we open up the wiki and save this there?

**Comment by bonelifer** [comment]
Sure

**Comment by romantomjak** [comment]
Created the wiki page [here](https://github.com/romantomjak/env-vault/wiki/Example-Makefile). Thanks for contributing!
