### ISSUE TITLE
password as param or passwordless

### ISSUE THREAD

**Issue by SerdarSanri** [romantomjak/env-vault#4]
Please add ability to create file without password or inline parameter so it can be easily used in ci/cd pipeline tools.

**Comment by romantomjak** [comment]
Thanks, that's a great suggestion! I've just released [v0.4.0](https://github.com/romantomjak/env-vault/releases/tag/v0.4.0) which should allow creating a vault without a password if `ENV_VAULT_PASSWORD` environment variable is set 🚀
